#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:

  ca.hulk.bx.com:
    image: hyperledger/fabric-ca:latest
    tty: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hulk.bx.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hulk.bx.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/hulk.bx.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../certificate-authority/ca-hulk:/etc/hyperledger/fabric-ca-server
    container_name: ca.hulk.bx.com
    networks:
      - basic

  ca.ironman.bx.com:
    image: hyperledger/fabric-ca:latest
    tty: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ironman.bx.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ironman.bx.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=9055
    ports:
      - "9055:9055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/ironman.bx.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../certificate-authority/ca-ironman:/etc/hyperledger/fabric-ca-server
    container_name: ca.ironman.bx.com
    networks:
      - basic

  ca.bx.com:
    image: hyperledger/fabric-ca:latest
    tty: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bx.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bx.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=9056
    ports:
      - "9056:9056"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/ordererOrganizations/bx.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../certificate-authority/ca-orderer:/etc/hyperledger/fabric-ca-server
    container_name: ca.bx.com
    networks:
      - basic

  orderer.bx.com:
    container_name: orderer.bx.com
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ../artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/bx.com/orderers/orderer.bx.com/msp/:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/bx.com/orderers/orderer.bx.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - basic

  peer0.hulk.bx.com:
    container_name: peer0.hulk.bx.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hulk.bx.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_LOCALMSPID=HulkMSP
      - CORE_PEER_ADDRESS=peer0.hulk.bx.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker-compose-files_basic
      # Peer specific values
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hulk.bx.com:7054
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7054
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hulk.bx.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hulk.bx.com:7051
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:19052
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      # Ledger configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=hulk-couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7054:7054
    volumes:
      - /var/run/:/host/var/run/
      - ./../crypto-config/peerOrganizations/hulk.bx.com/peers/peer0.hulk.bx.com/msp/:/etc/hyperledger/fabric/msp
      - ./../crypto-config/peerOrganizations/hulk.bx.com/peers/peer0.hulk.bx.com/tls/:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.bx.com
      - hulk-couchdb
    networks:
      - basic

  peer1.hulk.bx.com:
    container_name: peer1.hulk.bx.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.hulk.bx.com
      - CORE_PEER_NETWORKID=test
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_LOCALMSPID=HulkMSP
      - CORE_PEER_ADDRESS=peer1.hulk.bx.com:7061
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker-compose-files_basic
      # Peer specific values
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODEADDRESS=peer1.hulk.bx.com:7084
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7084
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hulk.bx.com:7061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hulk.bx.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:19052
      # Ledger configuration
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=hulk-couchdb:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7061:7061
      - 7084:7084
    volumes:
      - /var/run/:/host/var/run/
      - ./../crypto-config/peerOrganizations/hulk.bx.com/peers/peer1.hulk.bx.com/msp/:/etc/hyperledger/fabric/msp
      - ./../crypto-config/peerOrganizations/hulk.bx.com/peers/peer1.hulk.bx.com/tls/:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.bx.com
    networks:
      - basic

  hulk-cli:
    container_name: hulk-cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hulk.bx.com:7051
      - CORE_PEER_LOCALMSPID=HulkMSP
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer0.hulk.bx.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer0.hulk.bx.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer0.hulk.bx.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/users/Admin@hulk.bx.com/msp
      - ORDERER_TLS_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/bx.com/orderers/orderer.bx.com/msp/tlscacerts/tlsca.bx.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincodes:/opt/gopath/src/github.com/chaincode
      - ./../crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../artifacts/:/etc/hyperledger/artifacts
    networks:
        - basic
    depends_on:
      - orderer.bx.com
      - peer0.hulk.bx.com
  
  hulk-cli-peer1:
    container_name: hulk-cli-peer1
    image: hyperledger/fabric-tools:2.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.hulk.bx.com:7061
      - CORE_PEER_LOCALMSPID=HulkMSP
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer1.hulk.bx.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer1.hulk.bx.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/peers/peer1.hulk.bx.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hulk.bx.com/users/Admin@hulk.bx.com/msp
      - ORDERER_TLS_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/bx.com/orderers/orderer.bx.com/msp/tlscacerts/tlsca.bx.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincodes:/opt/gopath/src/github.com/chaincode
      - ./../crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../artifacts/:/etc/hyperledger/artifacts
    networks:
        - basic
    depends_on:
      - orderer.bx.com
      - peer1.hulk.bx.com

  peer0.ironman.bx.com:
    container_name: peer0.ironman.bx.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.ironman.bx.com
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_LOCALMSPID=IronmanMSP
      - CORE_PEER_ADDRESS=peer0.ironman.bx.com:7052
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker-compose-files_basic
      # Peer Specific Values
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_CHAINCODEADDRESS=peer0.ironman.bx.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ironman.bx.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ironman.bx.com:7052
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:19051
      # Ledger configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=ironman-couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7052:7052
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./../crypto-config/peerOrganizations/ironman.bx.com/peers/peer0.ironman.bx.com/msp/:/etc/hyperledger/fabric/msp
      - ./../crypto-config/peerOrganizations/ironman.bx.com/peers/peer0.ironman.bx.com/tls/:/etc/hyperledger/fabric/tls
    depends_on:
      - orderer.bx.com
      - ironman-couchdb
    networks:
      - basic

  ironman-cli:
    container_name: ironman-cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ironman.bx.com:7052
      - CORE_PEER_LOCALMSPID=IronmanMSP
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ironman.bx.com/peers/peer0.ironman.bx.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ironman.bx.com/peers/peer0.ironman.bx.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ironman.bx.com/peers/peer0.ironman.bx.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ironman.bx.com/users/Admin@ironman.bx.com/msp
      - ORDERER_TLS_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/bx.com/orderers/orderer.bx.com/msp/tlscacerts/tlsca.bx.com-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincodes:/opt/gopath/src/github.com/chaincode
      - ./../crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../artifacts/:/etc/hyperledger/artifacts
    networks:
        - basic
    depends_on:
      - orderer.bx.com
      - peer0.ironman.bx.com
  
  hulk-couchdb:
    container_name: hulk-couchdb
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - basic
  
  ironman-couchdb:
    container_name: ironman-couchdb
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5985:5984
    networks:
      - basic